### ISSUE TITLE
Hi-res filter 'Nearest' always applied on startup

### ISSUE THREAD

**Issue by AstudilloMarillo** [BGP0/ResolutionControl-3#3] opened 2024-07-18 11:24 UTC
When starting Minecraft, 'Nearest' is always automatically applied as the Hi-res filter, even if you had selected 'Linear'. You have to manually reselect 'Linear' every time to make it apply. Can you maybe fix this?

**Comment by InfinityMr** [comment] 2024-07-22 20:51
I saw a fix for this problem in one of the comments for the old Resolution Control mod. Fix is easy:

```
+++ b/src/main/java/io/github/ultimateboomer/resolutioncontrol/ResolutionControlMod.java
@@ -141,10 +141,12 @@ public class ResolutionControlMod implements ModInitializer {
                Window window = getWindow();
                if (framebuffer == null) {
                        this.shouldScale = true; // so we get the right dimensions
-                       framebuffer = new WindowFramebuffer(
-                                       window.getFramebufferWidth(),
-                                       window.getFramebufferHeight()
-                       );
+                       var w = window.getFramebufferWidth();
+                       var h = window.getFramebufferHeight();
+                       framebuffer = new WindowFramebuffer(w, h);
+
+                       // necessary to trigger initFbo() so that scaling algorithm is set correctly
+                       framebuffer.resize(w, h, MinecraftClient.IS_SYSTEM_MAC);
                        calculateSize();
                }
```

The issue is the framebuffer is being created without the scaling attributes being applied. A dummy call to resize() causes that to happen via initFbo().

**Comment by BGP0** [comment] 2024-07-24 09:34
ill add this when i next work on this mod so probably 1.22 or you can submit a pull request

**Comment by AstudilloMarillo** [comment] 2024-07-27 18:13
> or you can submit a pull request

Just did this

**Comment by BGP0** [comment] 2024-08-21 17:58
ill do it now :)

**Closed by BGP0** 2024-08-21 17:58 UTC

**Comment by AstudilloMarillo** [comment] 2024-08-23 17:32
Awesome, thanks!
